apiVersion: apps/v1
kind: Deployment
metadata:
  name: cable
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: cable
  template:
    metadata:
      labels:
        app: cable
    spec:
      containers:
        - name: cable
          image: akhonya/cable:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5 
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
